# Generated by Django 4.2.3 on 2023-11-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='category',
            field=models.CharField(choices=[('COMMUNITY', 'Community'), ('ORGANISATION', 'Organisation'), ('ENVIRONMENT', 'Environment')], max_length=100, null=True),
        ),
    ]
