# Generated by Django 4.2.3 on 2023-11-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_problem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='goal',
            field=models.ManyToManyField(blank=True, to='accounts.goal'),
        ),
    ]
