# Generated by Django 4.2.3 on 2023-11-21 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_problem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='title',
        ),
    ]
