# Generated by Django 4.2.3 on 2023-11-21 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_problem_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='goal',
        ),
        migrations.AlterField(
            model_name='problem',
            name='img_one',
            field=models.ImageField(blank=True, null=True, upload_to='problem/image'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='img_three',
            field=models.ImageField(blank=True, null=True, upload_to='problem/image'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='img_two',
            field=models.ImageField(blank=True, null=True, upload_to='problem/image'),
        ),
        migrations.AddField(
            model_name='problem',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.goal'),
        ),
    ]
