# Generated by Django 4.2.3 on 2023-11-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_problem_goal_alter_problem_img_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='idea',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
