# Generated by Django 5.0 on 2024-04-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_problem_dislikes_remove_problem_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
